apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging 
  namespace: techtrends
spec:
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml 
    path: project/helm/ 
    repoURL: https://github.com/trinhtrannp/nd064_course_1 
    targetRevision: HEAD